### ISSUE TITLE
Health system for enemies.

### ISSUE THREAD

**Issue by Martin31** [csuFresno-csci150-F18-L330-T3/postApocalypticRTS#15]

**Comment by rsteven46** [comment]
Are we going to have health bars for everything? @fredw21

**Comment by fredw21** [comment]
I assume so. Especially if we just keep it to a single unit type so that we meet deadlines. @rsteven46

**Comment by fredw21** [comment]
Added working health bars to all player and enemy units. All changes merged into copy-of-master. Ready for further use.
