### ISSUE TITLE
Enemy Base Generation

### ISSUE THREAD

**Issue by Martin31** [csuFresno-csci150-F18-L330-T3/postApocalypticRTS#23]
I made it possible to generate enemy bases, but there is nothing stopping them from spawning in the same location. @rsteven46 @fredw21

**Comment by JBaradin** [comment]
Fixed, also allows for spawning of any object, it will avoid bases and walls. I cloned your branch, let me know if you want me to merge it to yours or onto another.

**Comment by Martin31** [comment]
@JBaradin everything look good but the bases spawn outside the bounds of the world.

**Comment by JBaradin** [comment]
@Martin31 that's just the settings for the x,y limits, you can adjust them as need be for larger and smaller levels. Should work just fine, I just added some default values for testing.

**Comment by JBaradin** [comment]
It is currently, I'll add an adjustable avoidance measure to the player base tomorrow as well. Anything else in the generation we might need?

**Comment by Martin31** [comment]
I think that is it for now unless @JaceBlack needs something.
