### ISSUE TITLE
Player Base Lose Condition

### ISSUE THREAD

**Issue by JaceBlack** [csuFresno-csci150-F18-L330-T3/postApocalypticRTS#44]
Make bulding destroyable by enemies. Decrease detection radius of player base so that enemies have to be closer to base than units to start "chasing" it.  Set max unit cap and make them spawn units like enemy bases but take more time to spawn a unit. If all buildings are destroyed you lose. Only implement this if it works. If it does not work default to units are lose condition.

**Comment by Martin31** [comment]
Enemies now "chase" bases.

**Comment by Martin31** [comment]
The unit cap can be set now.

**Comment by Martin31** [comment]
@JaceBlack I added to the Stats tracker script that when the bases are gone it goes back to the Main Menu for now.
