### ISSUE TITLE
Updating Stationary Enemy AI

### ISSUE THREAD

**Issue by JBaradin** [csuFresno-csci150-F18-L330-T3/postApocalypticRTS#47]
Currently, enemies will only chase player units or the base within their range. Should we add some kind of wander function to them? Keep it slow, probably around 1/4th their chase speed or even less so that they don't completely swarm the map within 30 seconds.

**Comment by Martin31** [comment]
@JBaradin I was thinking of doing something about this, but if you want to work on it go ahead although I was thinking to see if it was possible for them to protect or patrol the base they spawned at. A simple solution could be that they move at random for a certain range.

**Comment by JBaradin** [comment]
Personally, I like the idea of the random movement, considering these things are some form of zombie. We could add a challenge aspect to it by slowly increasing their wander range, so as more spawn, they begin to take over more of the map. We'll probably have to discuss the best course of action in class.

**Comment by Martin31** [comment]
I was also thinking giving them a random speed for with in three values or so.

**Comment by JBaradin** [comment]
I think that could add some gameplay depth. @Martin31 Also, I've updated and added some generation scripts as well as implemented the base spawning into world gen so they'll no longer spawn in walls/on top of each other. I used your branch and edited a few things in the game scene (primarily removing your base spawn script and integrating it into the new one). Is it all right if I merge into MG-Working or do you want to review my changes on Tuesday?

**Comment by Martin31** [comment]
If it is okay with @JBaradin please publish your branch so I can review it.

**Comment by Martin31** [comment]
@JBaradin I merged your branch into mine and added a naming for the bases and enemies.

**Comment by Martin31** [comment]
I added a default movement in which they randomly go in a direction and if they collide with something they turn around and go the other way.
