### ISSUE TITLE
Update base and object spawning

### ISSUE THREAD

**Issue by JBaradin** [csuFresno-csci150-F18-L330-T3/postApocalypticRTS#52]
Updating the enemy base spawning so they don't spawn on top of the player base. I'm also going to create an adjustable script specifically for blueprint spawning, since allowing them to spawn closer to bases will promote combat.

**Comment by JBaradin** [comment]
@Martin31 updated wall generation to also avoid any objects with the PlayerBase tag in unity. Check the ProceduralGeneration branch for changes. I merged MG working into my branch before any changes were made so it should just change the wallgen script and the gamescene (added PlayerBase tag to helicopter).

**Comment by Martin31** [comment]
@JBaradin The PlayerBase tag can't be on the helicopter because the enemies will go after if they get too close and they will probably stay around there.

**Comment by JBaradin** [comment]
@Martin31 Fixed, helicopter now has Helicopter tag and I changed the code to include it, should be fine now. Close this if no other bugs pop up.
