### ISSUE TITLE
Unit Selection

### ISSUE THREAD

**Issue by JaceBlack** [csuFresno-csci150-F18-L330-T3/postApocalypticRTS#6]
Can draw a rectangle to the screen but can not implement the rectangle selecting a unit.

**Comment by rsteven46** [comment]
Everyone get on this we need this asap

**Comment by Martin31** [comment]
@fredw21 How does the unit selection work. I could not figure it out the unit just stays in place.

**Comment by fredw21** [comment]
@Martin31 Press "U" to add units. Press "1" to enter Unit Selection Mode. Here, you can then click on various units to select/deselect them. Press "2" to enter Unit Movement Mode. Here, you can then click anywhere on the screen and the selected units will go to that point, as they previously did.

**Comment by Martin31** [comment]
Ok, thanks.

**Comment by JaceBlack** [comment]
We can honestly have both methods though if they can work together. Rectangle for seleccting large groups and individual for grabbing only a few units from a group.

**Comment by fredw21** [comment]
Is your stuff on GitHub? I can try getting my stuff to work with it later today. My goal is to, at least on a side branch, have player units able to attack enemy units by the end of today.

**Comment by JaceBlack** [comment]
yeah its branched under RectUnitSelection

**Comment by JaceBlack** [comment]
It uses the UnitMovement, UnitSelection, and UnitSelectHelper scripts. I also had to edit the script execution order but it is still a bit buggy.

**Comment by Martin31** [comment]
There is merge conflicts between the RectUnitSelection and the master clone.

**Comment by Martin31** [comment]
It has been merged with the master clone

**Comment by Martin31** [comment]
I found potential problems first, it is a little annoying to draw a rectangle when selecting one unit. Next, if you have a group selected and you decide to select an other group the previous group is still selected and goes to the near the place where the new group is selected.
